// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blolzuklfiadbylomxvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb2x6dWtsZmlhZGJ5bG9teHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjg1NTgsImV4cCI6MjA2Mzg0NDU1OH0.F3oTmWnytbx8cRv3wdrpGcfYJeHMOTcXmPPBkuPO4hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);